# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cb7a68afa9d7d96ad9f729dd9c4751f76aca9879a02e68a8ce39256ec25657aaf17152d3cc206ecf75c08ae445d4317511d41a75c112328dbbaa24dfe822b8c7

test:
  secret_key_base: e6ced27b1d366dd304ea2f93749a4d6a0d3efb3e296829364a8fd137fd66a323ae08ca8472cdc9b5dff647f587b679dc8a8d88b7aec85243bb9d774b16f02efe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
